version: '3.9'
services:

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672

  db-postgresql:
    container_name: db-postgresql
    image: postgres
    environment:
      POSTGRES_DB: propostadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "propostadb"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    expose:
      - 5432

  proposta-config-server:
    image: proposta/config-server
    container_name: proposta-config-server
    ports:
      - "8888:8888"
    expose:
      - 8888

  proposta-app:
    image: proposta/app
    container_name: proposta-app
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s
    env_file:
      - "variables.env"
#    environment:
#      CONFIG_SERVER_URL: 'http://proposta-config-server:8888'
#      POSTGRES_URL: 'jdbc:postgresql://db-postgresql:5432/propostadb'
#      POSTGRES_PASSWORD: 'admin'
#      RABBITMQ_HOST: 'rabbit-mq'
#      RABBITMQ_PORT: '5672'
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      proposta-config-server:
        condition: service_started
      db-postgresql:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy

  proposta-analisecredito:
    image: proposta/analise-credito
    container_name: proposta-analisecredito
    restart: on-failure
    env_file:
      - "variables.env"
#    environment:
#      CONFIG_SERVER_URL: 'http://proposta-config-server:8888'
#      RABBITMQ_HOST: 'rabbit-mq'
#      RABBITMQ_PORT: '5672'
    ports:
      - "8081:8081"
    expose:
      - 8081
    depends_on:
      proposta-config-server:
        condition: service_started
      proposta-app:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy

  proposta-notificacao:
    image: proposta/notificacao
    container_name: proposta-notificacao
    restart: on-failure
    env_file:
      - "variables.env"
#    environment:
#      CONFIG_SERVER_URL: 'http://proposta-config-server:8888'
#      RABBITMQ_HOST: 'rabbit-mq'
#      RABBITMQ_PORT: '5672'
#      EMAIL_USERNAME: '${EMAIL_USER}'
#      EMAIL_PASSWORD: '${EMAIL_PASSWORD}'
    ports:
      - "8082:8082"
    expose:
      - 8082
    depends_on:
      proposta-config-server:
        condition: service_started
      proposta-app:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy